### ISSUE TITLE
cannot complie

### ISSUE THREAD

**Issue by OCTestX** [alorma/Compose-Settings#339]
### When I import this lib,cannot complie,

**this is my import code:**

`implementation("com.github.alorma.compose-settings:ui-tiles:2.6.0")`

**This is full throw track:**

```
> Task :run
23:55:56.648 [main] ERROR Core$Inc$GlobalExceptionHandler - The uncaught exception in thread main: 'androidx.compose.material3.ColorScheme androidx.compose.material3.ColorSchemeKt.lightColorScheme-w9eWueE$default(long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, int, java.lang.Object)'
java.lang.NoSuchMethodError: 'androidx.compose.material3.ColorScheme androidx.compose.material3.ColorSchemeKt.lightColorScheme-w9eWueE$default(long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, long, int, java.lang.Object)'
	at utils.Colors$ThemeColorScheme.<clinit>(Colors.kt:10) ~[UDTBrowser-1.0-SNAPSHOT.jar:?]
	at Main.Presenter(Main.kt:147) ~[UDTBrowser-1.0-SNAPSHOT.jar:?]
	at Main.Presenter(Main.kt:62) ~[UDTBrowser-1.0-SNAPSHOT.jar:?]
	at ui.core.UIComponent.Main(UIComponent.kt:16) ~[UDTBrowser-1.0-SNAPSHOT.jar:?]
	at ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:58) ~[UDTBrowser-1.0-SNAPSHOT.jar:?]
	at ComposableSingletons$MainKt$lambda-1$1.invoke(Main.kt:57) ~[UDTBrowser-1.0-SNAPSHOT.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:116) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.ComposeWindow$setContent$5.invoke(ComposeWindow.desktop.kt:156) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.ComposeWindow$setContent$5.invoke(ComposeWindow.desktop.kt:155) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.WindowContentLayout_desktopKt.WindowContentLayout(WindowContentLayout.desktop.kt:103) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.ComposeWindowPanel$setContent$3$1.invoke(ComposeWindowPanel.desktop.kt:141) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.ComposeWindowPanel$setContent$3$1.invoke(ComposeWindowPanel.desktop.kt:140) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.ComposeWindowPanel$setContent$3.invoke(ComposeWindowPanel.desktop.kt:138) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.ComposeWindowPanel$setContent$3.invoke(ComposeWindowPanel.desktop.kt:137) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeContainer$setContent$1$1.invoke(ComposeContainer.desktop.kt:327) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeContainer$setContent$1$1.invoke(ComposeContainer.desktop.kt:326) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeContainer_desktopKt.ProvideContainerCompositionLocals(ComposeContainer.desktop.kt:512) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeContainer_desktopKt.access$ProvideContainerCompositionLocals(ComposeContainer.desktop.kt:1) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeContainer$setContent$1.invoke(ComposeContainer.desktop.kt:326) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeContainer$setContent$1.invoke(ComposeContainer.desktop.kt:325) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1$1$1$1.invoke(ComposeSceneMediator.desktop.kt:489) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1$1$1$1.invoke(ComposeSceneMediator.desktop.kt:488) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.layout.OverlayLayout_skikoKt.OverlayLayout(OverlayLayout.skiko.kt:72) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.node.InteropContainerKt.TrackInteropContainer(InteropContainer.kt:67) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.SwingInteropContainer$invoke$1.invoke(SwingInteropContainer.desktop.kt:103) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.SwingInteropContainer$invoke$1.invoke(SwingInteropContainer.desktop.kt:102) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.SwingInteropContainer.invoke(SwingInteropContainer.desktop.kt:100) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1$1$1.invoke(ComposeSceneMediator.desktop.kt:488) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1$1$1.invoke(ComposeSceneMediator.desktop.kt:487) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:248) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.BaseComposeScene$setContent$1$2.invoke(BaseComposeScene.skiko.kt:142) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.BaseComposeScene$setContent$1$2.invoke(BaseComposeScene.skiko.kt:141) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.PlatformCompositionLocalsKt.ProvidePlatformCompositionLocals(PlatformCompositionLocals.kt:26) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1$2.invoke(Wrapper.skiko.kt:51) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1$2.invoke(Wrapper.skiko.kt:50) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:193) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1.invoke(Wrapper.skiko.kt:47) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1.invoke(Wrapper.skiko.kt:46) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:228) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:266) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.Wrapper_skikoKt.provide(Wrapper.skiko.kt:63) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.Wrapper_skikoKt.access$provide(Wrapper.skiko.kt:1) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2.invoke(Wrapper.skiko.kt:46) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2.invoke(Wrapper.skiko.kt:45) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:107) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jb.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:33) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3303) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.ComposerImpl.composeContent$runtime(Composer.kt:3236) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:725) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1071) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.platform.Wrapper_skikoKt.setContent(Wrapper.skiko.kt:45) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.MultiLayerComposeSceneImpl.createComposition(MultiLayerComposeScene.skiko.kt:209) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.BaseComposeScene.setContent(BaseComposeScene.skiko.kt:141) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1.invoke(ComposeSceneMediator.desktop.kt:487) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1.invoke(ComposeSceneMediator.desktop.kt:485) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeSceneMediator.onComponentAttached(ComposeSceneMediator.desktop.kt:457) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.scene.ComposeContainer.addNotify(ComposeContainer.desktop.kt:270) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.awt.ComposeWindowPanel.addNotify(ComposeWindowPanel.desktop.kt:118) ~[ui-desktop-1.6.11.jar:?]
	at java.desktop/java.awt.Container.addNotify(Container.java:2804) ~[?:?]
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4846) ~[?:?]
	at java.desktop/java.awt.Container.addNotify(Container.java:2804) ~[?:?]
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4846) ~[?:?]
	at java.desktop/java.awt.Container.addNotify(Container.java:2804) ~[?:?]
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4846) ~[?:?]
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:721) ~[?:?]
	at java.desktop/java.awt.Container.addNotify(Container.java:2804) ~[?:?]
	at java.desktop/java.awt.Window.addNotify(Window.java:791) ~[?:?]
	at java.desktop/java.awt.Frame.addNotify(Frame.java:495) ~[?:?]
	at java.desktop/java.awt.Window.pack(Window.java:829) ~[?:?]
	at androidx.compose.ui.util.Windows_desktopKt.setSizeImpl-6HolHcs(Windows.desktop.kt:116) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.util.Windows_desktopKt.setSizeSafely-hQcJfNw(Windows.desktop.kt:55) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.window.Window_desktopKt$Window$5.invoke(Window.desktop.kt:239) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.window.Window_desktopKt$Window$5.invoke(Window.desktop.kt:176) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:426) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.window.Window_desktopKt$Window$12$1.invoke(Window.desktop.kt:419) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:78) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.window.AwtWindow_desktopKt$AwtWindow$3.invoke(AwtWindow.desktop.kt:76) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:59) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2$performUpdate$1.invoke(UpdateEffect.desktop.kt:55) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2304) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:504) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:260) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke$performUpdate(UpdateEffect.desktop.kt:55) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:64) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.ui.util.UpdateEffect_desktopKt$UpdateEffect$2.invoke(UpdateEffect.desktop.kt:47) ~[ui-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:82) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionImpl$RememberEventDispatcher.dispatchRememberObservers(Composition.kt:1295) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:984) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1005) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1099) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:633) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:619) ~[runtime-desktop-1.6.11.jar:?]
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:221) ~[ui-desktop-1.6.11.jar:?]
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-2.0.20.jar:2.0.20-release-360]
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104) ~[kotlinx-coroutines-core-jvm-1.8.1.jar:?]
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720) ~[?:?]
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714) ~[?:?]
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399) ~[?:?]
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86) ~[?:?]
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101) ~[?:?]
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90) ~[?:?]

> Task :run FAILED

Execution failed for task ':run'.
> Process 'command '/home/octest/.jdks/corretto-18.0.2/bin/java'' finished with non-zero exit value 1
```

**Colors.kt:10:**

```
        private val blueColorScheme = lightColorScheme(
            primary = Color(0xFF3F51B5), // 深蓝色
            onPrimary = Color.White, // 主色上的文字颜色
            primaryContainer = Color(0xFFE8EAF6), // 主色的容器背景
            onPrimaryContainer = Color(0xFF3F51B5), // 主色容器上的文字颜色
            secondary = Color(0xFF03A9F4), // 辅助色
            onSecondary = Color.White, // 辅助色上的文字颜色
            secondaryContainer = Color(0xFFDFF4FF), // 辅助色的容器背景
            onSecondaryContainer = Color(0xFF03A9F4), // 辅助色容器上的文字颜色
            tertiary = Color(0xFF00BCD4), // 第三色
            onTertiary = Color.White, // 第三色上的文字颜色
            tertiaryContainer = Color(0xFFE0F7FA), // 第三色的容器背景
            onTertiaryContainer = Color(0xFF00BCD4), // 第三色容器上的文字颜色
            error = Color(0xFFB71C1C), // 错误色
            onError = Color.White, // 错误色上的文字颜色
            errorContainer = Color(0xFFFFCDD2), // 错误色的容器背景
            onErrorContainer = Color(0xFFB71C1C), // 错误色容器上的文字颜色
            background = Color.White, // 背景色
            onBackground = Color.Black, // 背景上的文字颜色
            surface = Color.White, // 表面色
            onSurface = Color.Black, // 表面色上的文字颜色
            inverseSurface = Color.Black, // 反转表面色
            inverseOnSurface = Color.White, // 反转表面色上的文字颜色
            inversePrimary = Color.White // 反转主色
        )
```

**Comment by OCTestX** [comment]
And I tried 2.5.0 version, it too.

**Comment by alorma** [comment]
Hi @OCTestX !

It's almost New Year's eve here!

Are you adding compose material3 dependency to the project?

Do you have a sample reproducible project?

**Comment by OCTestX** [comment]
Yep, this is

> https://github.com/OCTestX/TestComposeSettingsLib1

Maybe I need tell my environment:

![Screenshot_20250101_083347](https://github.com/user-attachments/assets/4ed1e0e1-11b9-4a10-831f-6bbe8303121f)

OpenJDK-22, Gradle-8.7

I just import these lib：

```
implementation("com.github.alorma.compose-settings:ui-tiles:2.6.0")
implementation("org.jetbrains.compose.material3:material3-desktop:1.2.1")
```

and use Material3Theme:

```
MaterialTheme(darkColorScheme()) {
}
```

**Thank you too， Happy New Year's**

**Comment by alorma** [comment]
Thanks. 

I will take a look as soon as I can.

**Comment by alorma** [comment]
Hi @OCTestX 

I've just checked.

The main cause of the problem is that (on the sample) you are using an old dependency for material3-desktop (1.2.1):

```
implementation("org.jetbrains.compose.material3:material3-desktop:1.2.1")
```

If you replace that with:

```
implementation(compose.material3)
```

Then everything is working without any compile error :)

**Comment by OCTestX** [comment]
Indeed, it solved, sorry, I'm still in high school and can't test and get back to you in time.
Thank you @alorma
